### PR TITLE
Dropping CoffeeScript and modern bundling

### PR DESCRIPTION
**Pull request by jacoscaz**
Hello @adamhooper . This is draft PR that aims to follow up to our conversation in #6 . For the time being I've done the following:

- dropped `coffeescript`
- converted the library to ES6 modules
- added rollup configured to produce UMD bundles

I'm now working on tests, which I can't seem to get working as ES6 modules. Comments and feedbacks are more than welcome.

### CODE REVIEW

**Comment by jacoscaz** [comment]
After a few improvements, here's the current situation:

- the `/es` folder contains the actual source code w/ native ES modules
- `babel` transpiles `/es` to `/lib`, converting the module syntax to `commonjs`
- `rollup` creates the `umd` bundles available at the root of the project
- `mocha` tests are hitting transpiled `commonjs` files in `/lib`

This gets us:

1. support for ES-compatible tools via the `/es` folder
2. support for ES-incompatible tools via the `/lib` folder
3. support for `<script>` tags via `/*.umd-bundle.*` files
4. support for the current `mocha` test suite

**Comment by jacoscaz** [comment]
There you go - I've cleaned up the commit log, moved `/es` to `/src`, rebuilt, retested. Thank _you_ for your time! Is there anything else you'd like to do or have me do before you would consider doing another release to NPM? No pressure meant or implied, just wondering whether there's more I can contribute. I _am_ going to use this as a dependency after all.

**Comment by jacoscaz** [comment]
I've noticed that those `umd` bundles had ballooned up in size after setting sourcemap generation to `inline` mode. I've reverted to having separate sourcemap files. However, given that there are now 4 different `umd`-related files in the project's root folder, I would move those to a dedicated `/umd` subfolder.

**Comment by adamhooper** [comment]
@jacoscaz I've published the updates as v0.6.0. Thank you ever so much!

**Comment by jacoscaz** [comment]
@adamhooper thank _you_! Looking forward to using this in my own project. I think you can close the long-standing #4 now :)

**Pull request merged**
