### PR TITLE
Major update to all dependencies, drops gulp (including bundling and minification)

### PR DESCRIPTION
**Pull request by jacoscaz**
Hello @adamhooper .

This PR updates all dependencies to their latest versions and changes gulp tasks accordingly. Additionally, PhantomJS has been deprecated and I've dropped browser-side testing as a consequence of that (I might work on adding it back using a different method).

This was needed to begin working on index strategies as I could not get `gulp` to run using the project as-is.

### CODE REVIEW

**Comment by jacoscaz** [comment]
Ordinarily, as the output of both the `coffeescript` compiler and of `browserify` has changed (ES6 `class` syntax is now natively supported everywhere), this would deserve a bump in the `major` part of the version. However, this project has not seen a `1.0.0` release yet, so I have only bumped the version up in its `minor` part to `0.4.0`.

**Comment by jacoscaz** [comment]
I would also suggest getting rid of `browserify` entirely as the responsibility of bundling and minifying has shifted towards application developers in recent years. I can do so in this PR if you think it's a good idea.

**Comment by adamhooper** [comment]
This is so exciting! I don't have time to examine fully until next week; but I'm 100% on board with the direction.

I wholeheartedly agree with nixing browserify. You are welcome to nix it as part of this pull request.

**Comment by jacoscaz** [comment]
@adamhooper I'm happy you approve. I've added a couple of new commits to this PR that gets rid of `gulp` entirely as `CoffeeScript` transpilation to `JavaScript` can be handled via the `coffeescript` compiler directly. I've modified the scripts section of the `package.json` file accordingly. No worries, I'm going to branch out of this one to start working on insert strategies. Take all the time you need.

**Comment by adamhooper** [comment]
I'm going to merge this but won't release it yet. There are a few more steps to undertake before release:

* Nix Bower
* Your "strategy" pull request
* Build and minify (using Webpack or Rollup)
* Publish a UMD version somewhere (maybe GitHub Pages) so we can continue using jsperf
* Update README

(... and someday down the road, switch to Typescript/ES6....)

**Comment by jacoscaz** [comment]
I would be happy to take care of these. We could track them in a dedicated project? "Modernizing js-sorted-set" or something like that.

> Publish a UMD version somewhere (maybe GitHub Pages) so we can continue using jsperf

Given the kind of library that this is, there might be a case to be made for a `UMD` bundle (both minified and not) to be the only product created by the `dist` process.

**Comment by jacoscaz** [comment]
I've had a look around and I would personally go for the following:

- keep using the `coffeescript` compiler directly to compile `/src` to `/dist`
- use `webpack` to bundle `/dist` into `/SortedSet.umd.js` and `/SortedSet.umd.min.js`

The rationale behind this is that it makes the build process as transparent as possible and as vendor-independent as possible. Should a better bundler come up in the future, you would be able to swap it in without having to replace some obscure `webpack-coffeescript-loader` plugin and stuff like that. An additional bonus is that this keeps configuration files to a minimum.

Admittedly I am heavily biased against what I perceive to be an insane amount of complexity in modern web development. This is merely a suggestion, I am happy to help in any case.

**Comment by adamhooper** [comment]
The problem with compiling separate files to `/dist` is that users may try to ... well ... _use_ them. This `/dist` solution may be ideal for Node users, it's a big distraction (and source of errors) for Webpack and Rollup users. In sum, I think bare-CoffeeScript does more harm than good.

@jacoscaz What are your goals with this project? Mine are:

* Node: loads quickly
* Browser: works well with bundlers
* Browser: works well with `<script>` tags
* (would be nice) Browser: tree-shaking deletes unused strategies, for a minimal bundle size

I think Webpack or Rollup is required to achieve all these goals. I see no extra value delivered by a "raw" CoffeeScript output.

(Really, there's no value to CoffeeScript at all. The Web has changed. We could convert all these files to JS and put them in `src/` and that'd give you the same thing as `dist/` has right now.)

**Comment by jacoscaz** [comment]
Hello @adamhooper!

My interest in this project has very little to do with the structure of its repo or how the distributable code is produced. I am planning to use it as a dependency in [quadstore](https://github.com/beautifulinteractions/node-quadstore/tree/feature/advanced-query-engine), a datastore that I am extending with a small streaming query engine.

My previous proposal was based on the assumption that you wanted to keep using `CoffeeScript`. I agree with getting rid of it. As far as node and browser support are concerned, I don't think libraries should concern themselves with transpiling and/or minifying their code at all. That is something that is best taken care of at the application level.

Shipping pre-made `UMD` bundles, however, is still useful for quick experimentation and use cases such as `jsperf`.  So, in light of your comment, I would:
1. get rid of `coffeescript` entirely
2. drop the `/src` vs. `/dist` folder structure
3. move raw JS under `/lib` or something like that
4. provide `webpack`-made `.umd.js` at the root level of the project
5. point the `main` property in `package.json` to `lib/SortedSet.js` and make sure that the `.umd.js` bundle doesn't get published to NPM via the `files` property

I am not fully up to date with the state of native JS modules but, from what I know, they are not stable or well-supported enough to be considered reliable.

My 2 cents!

**Comment by adamhooper** [comment]
I'm super-keen on 1, 2, 3 and 4. As for 5: actually, I think the expectation on the Web is that libraries are pre-bundled. (Transpilers usually are configured to ignore `node_modules/`, meaning it's up to the module maintainer -- in this case, me ;) -- to transpile, upload the transpiled+bundled code to npmjs.org, and advertise browser compatibility.)

Unlike 5 years ago, there are certainly tools out there that do the heavy lifting given a nice, ES6 `src/` directory. Rollup is one.

**Comment by jacoscaz** [comment]
> I'm super-keen on 1, 2, 3 and 4.

Nice! I might be able to work on these if you are ok with it.

> As for 5: actually, I think the expectation on the Web is that libraries are pre-bundled. (Transpilers usually are configured to ignore node_modules/, meaning it's up to the module maintainer -- in this case, me ;) -- to transpile, upload the transpiled+bundled code to npmjs.org, and advertise browser compatibility.)

In the case of libraries with their own dependencies, then yes, I concur. But `js-sorted-set` has no dependencies, so I don't think this applies. That said, happy to go with what you choose.

> Unlike 5 years ago, there are certainly tools out there that do the heavy lifting given a nice, ES6 src/ directory. Rollup is one.

I've been looking for an excuse to try `Rollup` for a while, now. This might be just it!

**Pull request merged**
